# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  datasource:
    url: jdbc:h2:file:./data/test
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  devtools:
    livereload:
      enabled: false
#  handlebars:
#    cache: false
logging:
  level:
    jdbc:
      sqltiming: "DEBUG"
      resultsettable: "DEBUG"

    org:
      springframework:
        boot:
          autoconfigure: "ERROR"

